apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      containers:
        - name: at-javamicrosservicos-questao6
          image: jpcaglianone/notifications-service
          ports:
            - containerPort: 8080
