name: Deploy Spring Boot to Kubernetes

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'  

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Build Docker image
        run: |
          docker build -t jpcaglianone/notifications-service:latest .  # Use seu nome de usuário e nome do aplicativo

      - name: Log in to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push jpcaglianone/notifications-service:latest  # Use seu nome de usuário e nome do aplicativo

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Set Kubernetes context
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }} 
        run: |
          echo "${KUBE_CONFIG_DATA}" | base64 --decode > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/notifications-service notifications-service=jpcaglianone/notifications-service:latest
          kubectl rollout status deployment/notifications-service
